name: Build and Package Executable

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install pyinstaller
        run: python -m pip install pyinstaller

      - name: Install dependencies
        run: python -m pip install -r src/requirements.txt

      - name: Build executable
        run: pyinstaller run.py # --onefile -w

      - name: Zip executable and config file
        run: |
          mkdir smash64-tsh
          cp dist/* smash64-tsh/
          cp src/config.yml smash64-tsh/
          powershell Compress-Archive -Path smash64-tsh/* -DestinationPath build.zip

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build.zip
